// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multi_mapping_test.proto

package net.badata.protobuf.converter.proto;

public final class MultiMappingProto {
  private MultiMappingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultiMappingFirstOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MultiMappingFirst)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>int64 longValue = 2;</code>
     */
    long getLongValue();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingFirst}
   */
  public  static final class MultiMappingFirst extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MultiMappingFirst)
      MultiMappingFirstOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiMappingFirst.newBuilder() to construct.
    private MultiMappingFirst(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiMappingFirst() {
      intValue_ = 0;
      longValue_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiMappingFirst(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              intValue_ = input.readInt32();
              break;
            }
            case 16: {

              longValue_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.class, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder.class);
    }

    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 2;
    private long longValue_;
    /**
     * <code>int64 longValue = 2;</code>
     */
    public long getLongValue() {
      return longValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intValue_ != 0) {
        output.writeInt32(1, intValue_);
      }
      if (longValue_ != 0L) {
        output.writeInt64(2, longValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (longValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst)) {
        return super.equals(obj);
      }
      net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst other = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst) obj;

      boolean result = true;
      result = result && (getIntValue()
          == other.getIntValue());
      result = result && (getLongValue()
          == other.getLongValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getIntValue();
      hash = (37 * hash) + LONGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingFirst}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MultiMappingFirst)
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.class, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder.class);
      }

      // Construct using net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        intValue_ = 0;

        longValue_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_descriptor;
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getDefaultInstanceForType() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance();
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst build() {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst buildPartial() {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst result = new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst(this);
        result.intValue_ = intValue_;
        result.longValue_ = longValue_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst) {
          return mergeFrom((net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst other) {
        if (other == net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance()) return this;
        if (other.getIntValue() != 0) {
          setIntValue(other.getIntValue());
        }
        if (other.getLongValue() != 0L) {
          setLongValue(other.getLongValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int intValue_ ;
      /**
       * <code>int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        
        intValue_ = 0;
        onChanged();
        return this;
      }

      private long longValue_ ;
      /**
       * <code>int64 longValue = 2;</code>
       */
      public long getLongValue() {
        return longValue_;
      }
      /**
       * <code>int64 longValue = 2;</code>
       */
      public Builder setLongValue(long value) {
        
        longValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longValue = 2;</code>
       */
      public Builder clearLongValue() {
        
        longValue_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MultiMappingFirst)
    }

    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MultiMappingFirst)
    private static final net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst();
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiMappingFirst>
        PARSER = new com.google.protobuf.AbstractParser<MultiMappingFirst>() {
      public MultiMappingFirst parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiMappingFirst(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiMappingFirst> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiMappingFirst> getParserForType() {
      return PARSER;
    }

    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultiMappingSecondOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MultiMappingSecond)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>int64 longValueChanged = 2;</code>
     */
    long getLongValueChanged();

    /**
     * <code>string unusableValue = 3;</code>
     */
    java.lang.String getUnusableValue();
    /**
     * <code>string unusableValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getUnusableValueBytes();
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingSecond}
   */
  public  static final class MultiMappingSecond extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MultiMappingSecond)
      MultiMappingSecondOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiMappingSecond.newBuilder() to construct.
    private MultiMappingSecond(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiMappingSecond() {
      intValue_ = 0;
      longValueChanged_ = 0L;
      unusableValue_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiMappingSecond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              intValue_ = input.readInt32();
              break;
            }
            case 16: {

              longValueChanged_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              unusableValue_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.class, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder.class);
    }

    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }

    public static final int LONGVALUECHANGED_FIELD_NUMBER = 2;
    private long longValueChanged_;
    /**
     * <code>int64 longValueChanged = 2;</code>
     */
    public long getLongValueChanged() {
      return longValueChanged_;
    }

    public static final int UNUSABLEVALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object unusableValue_;
    /**
     * <code>string unusableValue = 3;</code>
     */
    public java.lang.String getUnusableValue() {
      java.lang.Object ref = unusableValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unusableValue_ = s;
        return s;
      }
    }
    /**
     * <code>string unusableValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUnusableValueBytes() {
      java.lang.Object ref = unusableValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unusableValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intValue_ != 0) {
        output.writeInt32(1, intValue_);
      }
      if (longValueChanged_ != 0L) {
        output.writeInt64(2, longValueChanged_);
      }
      if (!getUnusableValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unusableValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (longValueChanged_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValueChanged_);
      }
      if (!getUnusableValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unusableValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond)) {
        return super.equals(obj);
      }
      net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond other = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond) obj;

      boolean result = true;
      result = result && (getIntValue()
          == other.getIntValue());
      result = result && (getLongValueChanged()
          == other.getLongValueChanged());
      result = result && getUnusableValue()
          .equals(other.getUnusableValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getIntValue();
      hash = (37 * hash) + LONGVALUECHANGED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongValueChanged());
      hash = (37 * hash) + UNUSABLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getUnusableValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingSecond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MultiMappingSecond)
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.class, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder.class);
      }

      // Construct using net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        intValue_ = 0;

        longValueChanged_ = 0L;

        unusableValue_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_descriptor;
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getDefaultInstanceForType() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.getDefaultInstance();
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond build() {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond buildPartial() {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond result = new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond(this);
        result.intValue_ = intValue_;
        result.longValueChanged_ = longValueChanged_;
        result.unusableValue_ = unusableValue_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond) {
          return mergeFrom((net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond other) {
        if (other == net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.getDefaultInstance()) return this;
        if (other.getIntValue() != 0) {
          setIntValue(other.getIntValue());
        }
        if (other.getLongValueChanged() != 0L) {
          setLongValueChanged(other.getLongValueChanged());
        }
        if (!other.getUnusableValue().isEmpty()) {
          unusableValue_ = other.unusableValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int intValue_ ;
      /**
       * <code>int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        
        intValue_ = 0;
        onChanged();
        return this;
      }

      private long longValueChanged_ ;
      /**
       * <code>int64 longValueChanged = 2;</code>
       */
      public long getLongValueChanged() {
        return longValueChanged_;
      }
      /**
       * <code>int64 longValueChanged = 2;</code>
       */
      public Builder setLongValueChanged(long value) {
        
        longValueChanged_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longValueChanged = 2;</code>
       */
      public Builder clearLongValueChanged() {
        
        longValueChanged_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object unusableValue_ = "";
      /**
       * <code>string unusableValue = 3;</code>
       */
      public java.lang.String getUnusableValue() {
        java.lang.Object ref = unusableValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unusableValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unusableValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUnusableValueBytes() {
        java.lang.Object ref = unusableValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unusableValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unusableValue = 3;</code>
       */
      public Builder setUnusableValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unusableValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unusableValue = 3;</code>
       */
      public Builder clearUnusableValue() {
        
        unusableValue_ = getDefaultInstance().getUnusableValue();
        onChanged();
        return this;
      }
      /**
       * <code>string unusableValue = 3;</code>
       */
      public Builder setUnusableValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unusableValue_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MultiMappingSecond)
    }

    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MultiMappingSecond)
    private static final net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond();
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiMappingSecond>
        PARSER = new com.google.protobuf.AbstractParser<MultiMappingSecond>() {
      public MultiMappingSecond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiMappingSecond(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiMappingSecond> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiMappingSecond> getParserForType() {
      return PARSER;
    }

    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultiMappingTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.badata.protobuf.converter.proto.MultiMappingTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    boolean hasMultiMappingValue();
    /**
     * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getMultiMappingValue();
    /**
     * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder getMultiMappingValueOrBuilder();

    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> 
        getMultiMappingListValueList();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getMultiMappingListValue(int index);
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    int getMultiMappingListValueCount();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    java.util.List<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder> 
        getMultiMappingListValueOrBuilderList();
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder getMultiMappingListValueOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingTest}
   */
  public  static final class MultiMappingTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.badata.protobuf.converter.proto.MultiMappingTest)
      MultiMappingTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiMappingTest.newBuilder() to construct.
    private MultiMappingTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiMappingTest() {
      multiMappingListValue_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiMappingTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder subBuilder = null;
              if (multiMappingValue_ != null) {
                subBuilder = multiMappingValue_.toBuilder();
              }
              multiMappingValue_ = input.readMessage(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(multiMappingValue_);
                multiMappingValue_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                multiMappingListValue_ = new java.util.ArrayList<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond>();
                mutable_bitField0_ |= 0x00000002;
              }
              multiMappingListValue_.add(
                  input.readMessage(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          multiMappingListValue_ = java.util.Collections.unmodifiableList(multiMappingListValue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.class, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.Builder.class);
    }

    private int bitField0_;
    public static final int MULTIMAPPINGVALUE_FIELD_NUMBER = 1;
    private net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst multiMappingValue_;
    /**
     * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    public boolean hasMultiMappingValue() {
      return multiMappingValue_ != null;
    }
    /**
     * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getMultiMappingValue() {
      return multiMappingValue_ == null ? net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance() : multiMappingValue_;
    }
    /**
     * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder getMultiMappingValueOrBuilder() {
      return getMultiMappingValue();
    }

    public static final int MULTIMAPPINGLISTVALUE_FIELD_NUMBER = 2;
    private java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> multiMappingListValue_;
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> getMultiMappingListValueList() {
      return multiMappingListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public java.util.List<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder> 
        getMultiMappingListValueOrBuilderList() {
      return multiMappingListValue_;
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public int getMultiMappingListValueCount() {
      return multiMappingListValue_.size();
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getMultiMappingListValue(int index) {
      return multiMappingListValue_.get(index);
    }
    /**
     * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
     */
    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder getMultiMappingListValueOrBuilder(
        int index) {
      return multiMappingListValue_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (multiMappingValue_ != null) {
        output.writeMessage(1, getMultiMappingValue());
      }
      for (int i = 0; i < multiMappingListValue_.size(); i++) {
        output.writeMessage(2, multiMappingListValue_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (multiMappingValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMultiMappingValue());
      }
      for (int i = 0; i < multiMappingListValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, multiMappingListValue_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest)) {
        return super.equals(obj);
      }
      net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest other = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest) obj;

      boolean result = true;
      result = result && (hasMultiMappingValue() == other.hasMultiMappingValue());
      if (hasMultiMappingValue()) {
        result = result && getMultiMappingValue()
            .equals(other.getMultiMappingValue());
      }
      result = result && getMultiMappingListValueList()
          .equals(other.getMultiMappingListValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMultiMappingValue()) {
        hash = (37 * hash) + MULTIMAPPINGVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getMultiMappingValue().hashCode();
      }
      if (getMultiMappingListValueCount() > 0) {
        hash = (37 * hash) + MULTIMAPPINGLISTVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getMultiMappingListValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.badata.protobuf.converter.proto.MultiMappingTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.badata.protobuf.converter.proto.MultiMappingTest)
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.class, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.Builder.class);
      }

      // Construct using net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMultiMappingListValueFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (multiMappingValueBuilder_ == null) {
          multiMappingValue_ = null;
        } else {
          multiMappingValue_ = null;
          multiMappingValueBuilder_ = null;
        }
        if (multiMappingListValueBuilder_ == null) {
          multiMappingListValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          multiMappingListValueBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_descriptor;
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest getDefaultInstanceForType() {
        return net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.getDefaultInstance();
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest build() {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest buildPartial() {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest result = new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (multiMappingValueBuilder_ == null) {
          result.multiMappingValue_ = multiMappingValue_;
        } else {
          result.multiMappingValue_ = multiMappingValueBuilder_.build();
        }
        if (multiMappingListValueBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            multiMappingListValue_ = java.util.Collections.unmodifiableList(multiMappingListValue_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.multiMappingListValue_ = multiMappingListValue_;
        } else {
          result.multiMappingListValue_ = multiMappingListValueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest) {
          return mergeFrom((net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest other) {
        if (other == net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest.getDefaultInstance()) return this;
        if (other.hasMultiMappingValue()) {
          mergeMultiMappingValue(other.getMultiMappingValue());
        }
        if (multiMappingListValueBuilder_ == null) {
          if (!other.multiMappingListValue_.isEmpty()) {
            if (multiMappingListValue_.isEmpty()) {
              multiMappingListValue_ = other.multiMappingListValue_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMultiMappingListValueIsMutable();
              multiMappingListValue_.addAll(other.multiMappingListValue_);
            }
            onChanged();
          }
        } else {
          if (!other.multiMappingListValue_.isEmpty()) {
            if (multiMappingListValueBuilder_.isEmpty()) {
              multiMappingListValueBuilder_.dispose();
              multiMappingListValueBuilder_ = null;
              multiMappingListValue_ = other.multiMappingListValue_;
              bitField0_ = (bitField0_ & ~0x00000002);
              multiMappingListValueBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMultiMappingListValueFieldBuilder() : null;
            } else {
              multiMappingListValueBuilder_.addAllMessages(other.multiMappingListValue_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst multiMappingValue_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder> multiMappingValueBuilder_;
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public boolean hasMultiMappingValue() {
        return multiMappingValueBuilder_ != null || multiMappingValue_ != null;
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst getMultiMappingValue() {
        if (multiMappingValueBuilder_ == null) {
          return multiMappingValue_ == null ? net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance() : multiMappingValue_;
        } else {
          return multiMappingValueBuilder_.getMessage();
        }
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder setMultiMappingValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst value) {
        if (multiMappingValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          multiMappingValue_ = value;
          onChanged();
        } else {
          multiMappingValueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder setMultiMappingValue(
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder builderForValue) {
        if (multiMappingValueBuilder_ == null) {
          multiMappingValue_ = builderForValue.build();
          onChanged();
        } else {
          multiMappingValueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder mergeMultiMappingValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst value) {
        if (multiMappingValueBuilder_ == null) {
          if (multiMappingValue_ != null) {
            multiMappingValue_ =
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.newBuilder(multiMappingValue_).mergeFrom(value).buildPartial();
          } else {
            multiMappingValue_ = value;
          }
          onChanged();
        } else {
          multiMappingValueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public Builder clearMultiMappingValue() {
        if (multiMappingValueBuilder_ == null) {
          multiMappingValue_ = null;
          onChanged();
        } else {
          multiMappingValue_ = null;
          multiMappingValueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder getMultiMappingValueBuilder() {
        
        onChanged();
        return getMultiMappingValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder getMultiMappingValueOrBuilder() {
        if (multiMappingValueBuilder_ != null) {
          return multiMappingValueBuilder_.getMessageOrBuilder();
        } else {
          return multiMappingValue_ == null ?
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.getDefaultInstance() : multiMappingValue_;
        }
      }
      /**
       * <code>.net.badata.protobuf.converter.proto.MultiMappingFirst multiMappingValue = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder> 
          getMultiMappingValueFieldBuilder() {
        if (multiMappingValueBuilder_ == null) {
          multiMappingValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirst.Builder, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingFirstOrBuilder>(
                  getMultiMappingValue(),
                  getParentForChildren(),
                  isClean());
          multiMappingValue_ = null;
        }
        return multiMappingValueBuilder_;
      }

      private java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> multiMappingListValue_ =
        java.util.Collections.emptyList();
      private void ensureMultiMappingListValueIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          multiMappingListValue_ = new java.util.ArrayList<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond>(multiMappingListValue_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder> multiMappingListValueBuilder_;

      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> getMultiMappingListValueList() {
        if (multiMappingListValueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(multiMappingListValue_);
        } else {
          return multiMappingListValueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public int getMultiMappingListValueCount() {
        if (multiMappingListValueBuilder_ == null) {
          return multiMappingListValue_.size();
        } else {
          return multiMappingListValueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond getMultiMappingListValue(int index) {
        if (multiMappingListValueBuilder_ == null) {
          return multiMappingListValue_.get(index);
        } else {
          return multiMappingListValueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder setMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
        if (multiMappingListValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.set(index, value);
          onChanged();
        } else {
          multiMappingListValueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder setMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
        if (multiMappingListValueBuilder_ == null) {
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.set(index, builderForValue.build());
          onChanged();
        } else {
          multiMappingListValueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
        if (multiMappingListValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.add(value);
          onChanged();
        } else {
          multiMappingListValueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond value) {
        if (multiMappingListValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.add(index, value);
          onChanged();
        } else {
          multiMappingListValueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
        if (multiMappingListValueBuilder_ == null) {
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.add(builderForValue.build());
          onChanged();
        } else {
          multiMappingListValueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addMultiMappingListValue(
          int index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder builderForValue) {
        if (multiMappingListValueBuilder_ == null) {
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.add(index, builderForValue.build());
          onChanged();
        } else {
          multiMappingListValueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder addAllMultiMappingListValue(
          java.lang.Iterable<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond> values) {
        if (multiMappingListValueBuilder_ == null) {
          ensureMultiMappingListValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, multiMappingListValue_);
          onChanged();
        } else {
          multiMappingListValueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder clearMultiMappingListValue() {
        if (multiMappingListValueBuilder_ == null) {
          multiMappingListValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          multiMappingListValueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public Builder removeMultiMappingListValue(int index) {
        if (multiMappingListValueBuilder_ == null) {
          ensureMultiMappingListValueIsMutable();
          multiMappingListValue_.remove(index);
          onChanged();
        } else {
          multiMappingListValueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder getMultiMappingListValueBuilder(
          int index) {
        return getMultiMappingListValueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder getMultiMappingListValueOrBuilder(
          int index) {
        if (multiMappingListValueBuilder_ == null) {
          return multiMappingListValue_.get(index);  } else {
          return multiMappingListValueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public java.util.List<? extends net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder> 
           getMultiMappingListValueOrBuilderList() {
        if (multiMappingListValueBuilder_ != null) {
          return multiMappingListValueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(multiMappingListValue_);
        }
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder addMultiMappingListValueBuilder() {
        return getMultiMappingListValueFieldBuilder().addBuilder(
            net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.getDefaultInstance());
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder addMultiMappingListValueBuilder(
          int index) {
        return getMultiMappingListValueFieldBuilder().addBuilder(
            index, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.getDefaultInstance());
      }
      /**
       * <code>repeated .net.badata.protobuf.converter.proto.MultiMappingSecond multiMappingListValue = 2;</code>
       */
      public java.util.List<net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder> 
           getMultiMappingListValueBuilderList() {
        return getMultiMappingListValueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder> 
          getMultiMappingListValueFieldBuilder() {
        if (multiMappingListValueBuilder_ == null) {
          multiMappingListValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecond.Builder, net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingSecondOrBuilder>(
                  multiMappingListValue_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          multiMappingListValue_ = null;
        }
        return multiMappingListValueBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.badata.protobuf.converter.proto.MultiMappingTest)
    }

    // @@protoc_insertion_point(class_scope:net.badata.protobuf.converter.proto.MultiMappingTest)
    private static final net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest();
    }

    public static net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiMappingTest>
        PARSER = new com.google.protobuf.AbstractParser<MultiMappingTest>() {
      public MultiMappingTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiMappingTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiMappingTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiMappingTest> getParserForType() {
      return PARSER;
    }

    public net.badata.protobuf.converter.proto.MultiMappingProto.MultiMappingTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030multi_mapping_test.proto\022#net.badata.p" +
      "rotobuf.converter.proto\"8\n\021MultiMappingF" +
      "irst\022\020\n\010intValue\030\001 \001(\005\022\021\n\tlongValue\030\002 \001(" +
      "\003\"W\n\022MultiMappingSecond\022\020\n\010intValue\030\001 \001(" +
      "\005\022\030\n\020longValueChanged\030\002 \001(\003\022\025\n\runusableV" +
      "alue\030\003 \001(\t\"\275\001\n\020MultiMappingTest\022Q\n\021multi" +
      "MappingValue\030\001 \001(\01326.net.badata.protobuf" +
      ".converter.proto.MultiMappingFirst\022V\n\025mu" +
      "ltiMappingListValue\030\002 \003(\01327.net.badata.p" +
      "rotobuf.converter.proto.MultiMappingSeco" +
      "ndB8\n#net.badata.protobuf.converter.prot" +
      "oB\021MultiMappingProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_badata_protobuf_converter_proto_MultiMappingFirst_descriptor,
        new java.lang.String[] { "IntValue", "LongValue", });
    internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_badata_protobuf_converter_proto_MultiMappingSecond_descriptor,
        new java.lang.String[] { "IntValue", "LongValueChanged", "UnusableValue", });
    internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_badata_protobuf_converter_proto_MultiMappingTest_descriptor,
        new java.lang.String[] { "MultiMappingValue", "MultiMappingListValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
